name = "advent25"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["advent25"]

[[depends-on]]
advent = "~0.1.0-dev"

[[pins]]
advent = { path='../advent' }

[build-switches]
release.optimization = ["-gnatn2", "-gnatp", "-O2", "-march=native"]
