name = "advent24"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["advent24"]

[[depends-on]]
ansiada = "^1.0.0"

[build-switches]
release.optimization = ["-gnatn2", "-gnatp", "-march=native", "-O3"]

[[depends-on]]
advent = "~0.1.0-dev"

[[pins]]
advent = { path='../advent' }
