name = "advent2016"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["main"]

[build-switches]
release.optimization = ["-O3", "-gnatn", "-gnatp", "-march=native"]

[[depends-on]]
advent = "~0.1.0-dev"

[[pins]]
advent = { path='../advent' }
