name = "advent"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

[[depends-on]]
ansiada = "^1.1.0"
